spring.application.name=Pokemon Card Collection
# datasource PostgreSQl
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/pokemon_card_collection_db
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}

# jpa
spring.jpa.database=postgresql
spring.jpa.show-sql=true

# generate schema ddl to create tables
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

# database initialization with data.sql after hibernate
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true